dotenv: .env
# automatically fetch contract sources from Etherscan
autofetch_sources: True

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    remappings:
      - "@openzeppelin-upgradable=lib/openzeppelin-contracts-upgradeable/"
      - "@openzeppelin=lib/openzeppelin-contracts/"
      - "ds-test=lib/ds-test/src/"
      - "solmate=lib/solmate/src/"
