[default]
src = 'contracts'
out = 'out'
test = 'test' 
libs = ['lib']
gas_reports = ['*']
optimizer = true
optimizer_runs = 10000
solc_version = '0.8.7'
# See more config options https://github.com/gakonst/foundry/tree/master/config