[default]
src = 'contracts'
out = 'out'
test = 'test' 
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
gas_reports = ['*']
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config